
[functions.aprovar-usuario]
enabled = true
verify_jwt = true
import_map = "./functions/aprovar-usuario/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/aprovar-usuario/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/aprovar-usuario/*.html" ]

[functions.definir-senha-definitiva]
enabled = true
verify_jwt = true
import_map = "./functions/definir-senha-definitiva/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/definir-senha-definitiva/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/definir-senha-definitiva/*.html" ]
