
[functions.aprovar-usuario]
enabled = true
verify_jwt = true
import_map = "./functions/aprovar-usuario/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/aprovar-usuario/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/aprovar-usuario/*.html" ]

[functions.definir-senha-definitiva]
enabled = true
verify_jwt = true
import_map = "./functions/definir-senha-definitiva/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/definir-senha-definitiva/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/definir-senha-definitiva/*.html" ]

[functions.redefinir-senha]
enabled = true
verify_jwt = true
import_map = "./functions/redefinir-senha/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/redefinir-senha/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/redefinir-senha/*.html" ]

[functions.solicitar-redefinicao-admin]
enabled = true
verify_jwt = true
import_map = "./functions/solicitar-redefinicao-admin/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/solicitar-redefinicao-admin/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/solicitar-redefinicao-admin/*.html" ]

[functions.marcar-redefinicao-senha]
enabled = true
verify_jwt = true
import_map = "./functions/marcar-redefinicao-senha/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/marcar-redefinicao-senha/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/marcar-redefinicao-senha/*.html" ]

[functions.solicitar-redefinicao]
enabled = true
verify_jwt = true
import_map = "./functions/solicitar-redefinicao/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/solicitar-redefinicao/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/solicitar-redefinicao/*.html" ]

[functions.alterar-senha]
enabled = true
verify_jwt = true
import_map = "./functions/alterar-senha/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/alterar-senha/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/alterar-senha/*.html" ]
