name: cloudtrack
description: "App de gerenciamento logístico com Supabase e Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  url_strategy: ^0.2.0

  # Ícones do iOS
  cupertino_icons: ^1.0.8

  # Banco de dados e autenticação
  supabase_flutter: ^2.10.3

  # Variáveis de ambiente (.env)
  flutter_dotenv: ^6.0.0

  # Animações e melhorias visuais (opcional, mas útil para futuras telas)
  flutter_animate: ^4.5.0
  dio: ^5.9.0
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  universal_html: ^2.2.4
  mask_text_input_formatter: ^2.9.0

  pdf: ^3.10.4
  universal_io: ^2.3.0  # Para detectar plataforma
  mime: ^1.0.4
  http: ^1.1.0  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_top_home.png
    - assets/background_login.jpg
    - assets/logo_top_login.png